import React from "react";
import { motion } from "framer-motion";
import {
  Heart,
  Brain,
  Shield,
  Users,
  Sparkles,
  CheckCircle,
  AlertTriangle,
} from "lucide-react";

const About = () => {
  const features = [
    {
      icon: Heart,
      title: "Compassionate AI",
      description:
        "Our AI is designed with empathy and understanding to provide supportive conversations.",
    },
    {
      icon: Brain,
      title: "Evidence-Based Responses",
      description:
        "Responses are grounded in established mental health and spiritual wellness principles.",
    },
    {
      icon: Shield,
      title: "Privacy First",
      description:
        "Your conversations are private and secure. We prioritize your confidentiality.",
    },
    {
      icon: Users,
      title: "Accessible Support",
      description:
        "24/7 availability for when you need someone to talk to, wherever you are.",
    },
  ];

  const limitations = [
    "Cannot provide medical diagnoses or replace professional therapy",
    "Not suitable for crisis situations requiring immediate intervention",
    "Responses are generated by AI and may not always be perfect",
    "Cannot prescribe medications or provide medical treatment",
    "Should complement, not replace, professional mental health care",
  ];

  const teamValues = [
    {
      title: "Compassion",
      description:
        "We believe in the power of empathetic listening and understanding.",
    },
    {
      title: "Accessibility",
      description:
        "Mental health and spiritual support should be available to everyone.",
    },
    {
      title: "Respect",
      description: "We honor all spiritual traditions and individual beliefs.",
    },
    {
      title: "Growth",
      description: "We support personal development and spiritual evolution.",
    },
  ];

  return (
    <div className="min-h-screen pt-20 bg-gradient-to-br from-tranquil-50 to-tranquil-50">
      {/* Header */}
      <section className="section-padding">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h1 className="text-4xl md:text-5xl font-heading font-bold text-mindful-900 mb-6">
              About Our Service
            </h1>
            <p className="text-lg md:text-xl text-mindful-600 leading-relaxed">
              We provide AI-powered support for mental health and spiritual
              wellness, creating a safe space for exploration, growth, and
              healing.
            </p>
          </motion.div>

          {/* Mission */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="card-elevated p-8 md:p-12 text-center mb-16"
          >
            <div className="w-16 h-16 bg-gradient-to-br from-tranquil-400 to-tranquil-600 rounded-3xl flex items-center justify-center mx-auto mb-6">
              <Sparkles className="w-8 h-8 text-white" />
            </div>
            <h2 className="text-2xl md:text-3xl font-heading font-bold text-mindful-900 mb-4">
              Our Mission
            </h2>
            <p className="text-lg text-mindful-600 leading-relaxed max-w-2xl mx-auto">
              To provide accessible, compassionate AI support that complements
              professional mental health care and spiritual guidance, helping
              individuals find peace, understanding, and growth on their
              personal journeys.
            </p>
          </motion.div>

          {/* Features */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="card p-6 text-center"
              >
                <div className="w-12 h-12 bg-gradient-to-br from-tranquil-400 to-tranquil-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-lg font-heading font-semibold text-mindful-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-mindful-600 text-sm leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* AI Capabilities and Limitations */}
      <section className="section-padding bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl md:text-4xl font-heading font-bold text-mindful-900 mb-4">
              AI Capabilities & Limitations
            </h2>
            <p className="text-lg text-mindful-600 max-w-2xl mx-auto">
              Understanding what our AI can and cannot do helps set appropriate
              expectations for your experience.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* What We Can Do */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              className="card p-8"
            >
              <div className="flex items-center mb-6">
                <CheckCircle className="w-6 h-6 text-tranquil-600 mr-3" />
                <h3 className="text-xl font-heading font-semibold text-mindful-900">
                  What We Can Do
                </h3>
              </div>
              <ul className="space-y-3">
                <li className="flex items-start">
                  <CheckCircle className="w-4 h-4 text-tranquil-500 mt-1 mr-3 flex-shrink-0" />
                  <span className="text-mindful-700">
                    Provide supportive conversations and active listening
                  </span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-4 h-4 text-tranquil-500 mt-1 mr-3 flex-shrink-0" />
                  <span className="text-mindful-700">
                    Offer coping strategies and mindfulness techniques
                  </span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-4 h-4 text-tranquil-500 mt-1 mr-3 flex-shrink-0" />
                  <span className="text-mindful-700">
                    Discuss spiritual questions and philosophical topics
                  </span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-4 h-4 text-tranquil-500 mt-1 mr-3 flex-shrink-0" />
                  <span className="text-mindful-700">
                    Provide general mental health information
                  </span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="w-4 h-4 text-tranquil-500 mt-1 mr-3 flex-shrink-0" />
                  <span className="text-mindful-700">
                    Help explore thoughts and feelings in a safe space
                  </span>
                </li>
              </ul>
            </motion.div>

            {/* Limitations */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              className="card p-8 border-l-4 border-warm-400"
            >
              <div className="flex items-center mb-6">
                <AlertTriangle className="w-6 h-6 text-warm-600 mr-3" />
                <h3 className="text-xl font-heading font-semibold text-mindful-900">
                  Important Limitations
                </h3>
              </div>
              <ul className="space-y-3">
                {limitations.map((limitation, index) => (
                  <li key={index} className="flex items-start">
                    <AlertTriangle className="w-4 h-4 text-warm-500 mt-1 mr-3 flex-shrink-0" />
                    <span className="text-mindful-700">{limitation}</span>
                  </li>
                ))}
              </ul>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Our Values */}
      <section className="section-padding bg-gradient-to-br from-tranquil-50 to-tranquil-50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl md:text-4xl font-heading font-bold text-mindful-900 mb-4">
              Our Values
            </h2>
            <p className="text-lg text-mindful-600 max-w-2xl mx-auto">
              These core values guide everything we do and shape how our AI
              interacts with you.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {teamValues.map((value, index) => (
              <motion.div
                key={value.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="card p-6 text-center"
              >
                <h3 className="text-lg font-heading font-semibold text-mindful-900 mb-3">
                  {value.title}
                </h3>
                <p className="text-mindful-600 text-sm leading-relaxed">
                  {value.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Privacy & Data Handling */}
      <section className="section-padding bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto"
          >
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-heading font-bold text-mindful-900 mb-4">
                Privacy & Data Handling
              </h2>
              <p className="text-lg text-mindful-600">
                Your privacy and security are our top priorities.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="card p-6">
                <h3 className="text-xl font-heading font-semibold text-mindful-900 mb-4">
                  Data Protection
                </h3>
                <ul className="space-y-2 text-mindful-700">
                  <li>• Conversations are encrypted and secure</li>
                  <li>• No personal data is stored permanently</li>
                  <li>• Chat history is only kept during your session</li>
                  <li>• No sharing of conversations with third parties</li>
                </ul>
              </div>

              <div className="card p-6">
                <h3 className="text-xl font-heading font-semibold text-mindful-900 mb-4">
                  Your Rights
                </h3>
                <ul className="space-y-2 text-mindful-700">
                  <li>• Clear your chat history at any time</li>
                  <li>• No account creation required</li>
                  <li>• Anonymous usage supported</li>
                  <li>• Full control over your data</li>
                </ul>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default About;
